[package]
name = "gpclient"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../../crates/common" }
gpapi = { path = "../../crates/gpapi", features = ["clap"] }
openconnect = { path = "../../crates/openconnect" }

anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
inquire = "0.7"
log.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
sysinfo.workspace = true
serde_json.workspace = true
whoami.workspace = true
tempfile.workspace = true
reqwest.workspace = true
directories.workspace = true
compile-time.workspace = true

[features]
default = ["webview-auth"]
webview-auth = ["gpapi/webview-auth"]
